### PR TITLE
Design changes to Filter & Details page

### PR DESCRIPTION
**Pull request by rasagy**
**Ready to be merged**

- [x] Sticky buttons now have a white background (after scrolling)
- [x] Buttons with keyboard shortcuts have the character <u>u</u>nderlined
- [x] Keycodes in js have their key added as a comment
- [x] Footer is now center-aligned to not conflict with the `Open in new window` link from the changeset map
- [x] Consistent labels in Filter page
- [x] Minor tweaks in the spacing around the layout
- [ ] Get feedback on type hierarchy & layout and make any more changes

### CODE REVIEW

**Comment by batpad** [comment]
@rasagy just pinging here to see how things look / if you would like to stage any of this?

**Comment by rasagy** [comment]
@batpad Will finish adding some tooltips today and then let’s check it on staging and see if it works?

**Comment by rasagy** [comment]
@amishas157 Can you have a look and merge this if everything looks fine? :)

**Comment by amishas157** [comment]
@rasagy This looks great 👍 . Just rebasing it with master and merging it then.

**Comment by amishas157** [comment]
Here are some screenshots from @rasagy's Design fixes. 
 - Underlined keyboard shortcuts

screen shot 2016-12-06 at 5 19 25 pm

- Sticky buttons with a white background 

screen shot 2016-12-06 at 5 50 22 pm


- Center aligned footer 

screen shot 2016-12-06 at 5 50 32 pm

- Consistent labels in filter page

screen shot 2016-12-06 at 6 03 23 pm

**Pull request merged**
